apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
  labels:
    app: fast-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api  # Service will lookup these labels
    spec:
      containers:
      - name: fast-api-pod
        image: iiakyjiuh/k8s-example:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi  
---
apiVersion: v1
kind: Service
metadata:
  name: fast-api    # selects pods with this label
spec:
  type: NodePort
  selector:
    app: fast-api
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # POD's port
      nodePort: 30100
